In [1]:
from src.training.fine_tuning.data_module import FineTuningDataModule

## PHQ8 score

In [2]:
data_module = FineTuningDataModule(fast_mode=False, target_column_name='phq_score', batch_size=4)
data_module.setup()
diter = iter(data_module.train_dataloader())

2024-09-13 09:38:43.204 | INFO     | src.training.fine_tuning.data_module:load_df:76 - Using dataset at /workspace/speech-based-distress-recognition/data/preprocessed_data/data.csv with split data at /workspace/speech-based-distress-recognition/data/preprocessed_data/split.csv
2024-09-13 09:38:43.331 | INFO     | src.training.fine_tuning.data_module:setup:118 - Setting up FineTuningDataModule without specifying train and val indices. Training data will be split into train ad val split with stratification with each group appearing in only one dataset if possible.
2024-09-13 09:38:43.339 | WARNING  | src.training.fine_tuning.data_module:setup:136 - Failed to stratify splits.
2024-09-13 09:38:43.344 | INFO     | src.training.fine_tuning.data_module:setup:147 - Mean target value among splits: train - 6.98, val - 5.50, test - 7.41.
2024-09-13 09:38:43.347 | INFO     | src.training.fine_tuning.dataset:__init__:116 - Dataset is initialized in RAM-optimised mode. Waveforms (157) will be loaded

In [3]:
next(diter)

[(tensor([[-453, -513, -623,  ...,  632,  134, -394]], dtype=torch.int16),
  16000,
  7.0),
 (tensor([[ 19,  19,  18,  ..., 140, 312, 328]], dtype=torch.int16),
  16000,
  7.0),
 (tensor([[ -9,  -9,  -9,  ..., -26, -21, -23]], dtype=torch.int16),
  16000,
  8.0),
 (tensor([[ 23,   5,  -1,  ..., 183, -26, -79]], dtype=torch.int16),
  16000,
  18.0)]

## PHQ binary

In [4]:
data_module = FineTuningDataModule(fast_mode=False, target_column_name='phq_binary', batch_size=4)
data_module.setup()
diter = iter(data_module.train_dataloader())

2024-09-13 09:38:44.072 | INFO     | src.training.fine_tuning.data_module:load_df:76 - Using dataset at /workspace/speech-based-distress-recognition/data/preprocessed_data/data.csv with split data at /workspace/speech-based-distress-recognition/data/preprocessed_data/split.csv
2024-09-13 09:38:44.205 | INFO     | src.training.fine_tuning.data_module:setup:118 - Setting up FineTuningDataModule without specifying train and val indices. Training data will be split into train ad val split with stratification with each group appearing in only one dataset if possible.
2024-09-13 09:38:44.217 | INFO     | src.training.fine_tuning.data_module:setup:147 - Mean target value among splits: train - 0.21, val - 0.30, test - 0.23.
2024-09-13 09:38:44.221 | INFO     | src.training.fine_tuning.dataset:__init__:116 - Dataset is initialized in RAM-optimised mode. Waveforms (157) will be loaded on-the-fly at each training step.
2024-09-13 09:38:44.223 | INFO     | src.training.fine_tuning.dataset:__init__

In [5]:
next(diter)

[(tensor([[-11,  -8,  -7,  ...,  60,  77,  75]], dtype=torch.int16),
  16000,
  0.0),
 (tensor([[12, 10, 12,  ..., 67, 69, 74]], dtype=torch.int16), 16000, 0.0),
 (tensor([[-14, -15, -15,  ..., -25, -24, -24]], dtype=torch.int16),
  48000,
  0.0),
 (tensor([[-15, -13, -14,  ..., -16,   2,   9]], dtype=torch.int16),
  16000,
  0.0)]